### ISSUE TITLE
Parameters not passed properly

### ISSUE THREAD

**Issue by mdangear** [cmacclang/cmacc-compiler#4]
Also submitted here: https://github.com/cmacclang/cmacc-lib-us/issues/6

See _test.cmacc in cmacc-lib-us.

The person full_Name is “{{first_Name}} {{last+Name}}“, but then when it gets passed to _entity_individual.cmacc is does not seem to be passed.

So I get “undefined undefined” instead
There is a workaround provided but it defeats the purpose of having the _entity_individual.cmacc file, so cannot work.

**Comment by wilmveel** [comment]
Fixed
